name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    
    steps:
    - name: waka-readme-stats
      uses: miermontoto/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_PROFILE_VIEWS: "False"
        SHOW_EDITORS: "False"
        SHOW_TIMEZONE: "False"
        SHOW_LANGUAGE_PER_REPO: "False"
        SHOW_SHORT_INFO: "False"
        SHOW_LOC_CHART: "False"

